import type { Scenario } from './types';

export const builtInScenarios: Scenario[] = [
  {
    id: 'fresh-installation',
    name: 'Fresh Installation',
    description: 'Brand new user — no memories, no discoveries, empty notebook, first launch.',
    category: 'experience',
    version: '1.0.0',
    compatibleVersion: '0.1.0',
    createdAt: '2025-01-01T00:00:00Z',
    author: 'system',
    components: [
      { type: 'runtime', data: { state: 'idle' } },
      { type: 'relationship', data: { trustScore: 5, stage: 'first_meet', sharedExperienceCount: 0, timeTogetherDays: 0 } },
      { type: 'memory', data: { count: 0 } },
      { type: 'discovery', data: { count: 0, pending: 0 } },
      { type: 'journey', data: { count: 0 } },
      { type: 'notebook', data: { pageCount: 0 } },
      { type: 'reflection', data: { count: 0 } },
      { type: 'notification', data: { queueSize: 0 } },
    ],
  },
  {
    id: 'first-day',
    name: 'First Day',
    description: 'Validate onboarding — first discovery assigned, notebook created, initial relationship.',
    category: 'experience',
    version: '1.0.0',
    compatibleVersion: '0.1.0',
    createdAt: '2025-01-01T00:00:00Z',
    author: 'system',
    components: [
      { type: 'runtime', data: { state: 'observe' } },
      { type: 'relationship', data: { trustScore: 10, stage: 'first_meet', sharedExperienceCount: 1, timeTogetherDays: 1 } },
      { type: 'memory', data: { count: 2 } },
      { type: 'discovery', data: { count: 1, pending: 1 } },
      { type: 'journey', data: { count: 1, active: 1 } },
      { type: 'notebook', data: { pageCount: 2 } },
      { type: 'reflection', data: { count: 1 } },
      { type: 'notification', data: { queueSize: 1 } },
    ],
  },
  {
    id: 'one-week',
    name: 'One Week Together',
    description: 'Validate early companionship — several discoveries, daily reflections, growing notebook.',
    category: 'experience',
    version: '1.0.0',
    compatibleVersion: '0.1.0',
    createdAt: '2025-01-01T00:00:00Z',
    author: 'system',
    components: [
      { type: 'runtime', data: { state: 'observe' } },
      { type: 'relationship', data: { trustScore: 25, stage: 'getting_familiar', sharedExperienceCount: 8, timeTogetherDays: 7 } },
      { type: 'memory', data: { count: 12 } },
      { type: 'discovery', data: { count: 7, pending: 2 } },
      { type: 'journey', data: { count: 2, active: 1 } },
      { type: 'notebook', data: { pageCount: 10 } },
      { type: 'reflection', data: { count: 7 } },
      { type: 'notification', data: { queueSize: 0 } },
    ],
  },
  {
    id: 'one-month',
    name: 'One Month Together',
    description: 'Validate medium-term — rich notebook, multiple journeys, discovery history, stronger relationship.',
    category: 'experience',
    version: '1.0.0',
    compatibleVersion: '0.1.0',
    createdAt: '2025-01-01T00:00:00Z',
    author: 'system',
    components: [
      { type: 'runtime', data: { state: 'observe' } },
      { type: 'relationship', data: { trustScore: 50, stage: 'trusted_companion', sharedExperienceCount: 25, timeTogetherDays: 30 } },
      { type: 'memory', data: { count: 40 } },
      { type: 'discovery', data: { count: 25, pending: 3 } },
      { type: 'journey', data: { count: 4, active: 2 } },
      { type: 'notebook', data: { pageCount: 35 } },
      { type: 'reflection', data: { count: 25 } },
      { type: 'notification', data: { queueSize: 0 } },
    ],
  },
  {
    id: 'long-term',
    name: 'Long-term Companion',
    description: 'Validate mature experience — large memory base, active long-term projects, deep relationship.',
    category: 'experience',
    version: '1.0.0',
    compatibleVersion: '0.1.0',
    createdAt: '2025-01-01T00:00:00Z',
    author: 'system',
    components: [
      { type: 'runtime', data: { state: 'observe' } },
      { type: 'relationship', data: { trustScore: 80, stage: 'long_term_companion', sharedExperienceCount: 80, timeTogetherDays: 120 } },
      { type: 'memory', data: { count: 150 } },
      { type: 'discovery', data: { count: 80, pending: 5 } },
      { type: 'journey', data: { count: 8, active: 3 } },
      { type: 'notebook', data: { pageCount: 100 } },
      { type: 'reflection', data: { count: 80 } },
      { type: 'notification', data: { queueSize: 0 } },
    ],
  },
  {
    id: 'return-after-absence',
    name: 'Return After Long Absence',
    description: 'Validate return — user absent, pending discoveries, missed reflections, welcome back.',
    category: 'experience',
    version: '1.0.0',
    compatibleVersion: '0.1.0',
    createdAt: '2025-01-01T00:00:00Z',
    author: 'system',
    components: [
      { type: 'runtime', data: { state: 'wake' } },
      { type: 'relationship', data: { trustScore: 45, stage: 'getting_familiar', sharedExperienceCount: 15, timeTogetherDays: 30 } },
      { type: 'memory', data: { count: 20 } },
      { type: 'discovery', data: { count: 10, pending: 5 } },
      { type: 'journey', data: { count: 2, active: 1 } },
      { type: 'notebook', data: { pageCount: 15 } },
      { type: 'reflection', data: { count: 5, pending: 3 } },
      { type: 'notification', data: { queueSize: 2 } },
    ],
  },
  {
    id: 'heavy-discovery',
    name: 'Heavy Discovery',
    description: 'Stress test — large discovery queue, multiple cards, notebook updates, prioritization.',
    category: 'development',
    version: '1.0.0',
    compatibleVersion: '0.1.0',
    createdAt: '2025-01-01T00:00:00Z',
    author: 'system',
    components: [
      { type: 'runtime', data: { state: 'observe' } },
      { type: 'relationship', data: { trustScore: 40, stage: 'getting_familiar', sharedExperienceCount: 10 } },
      { type: 'memory', data: { count: 30 } },
      { type: 'discovery', data: { count: 50, pending: 15 } },
      { type: 'journey', data: { count: 2, active: 1 } },
      { type: 'notebook', data: { pageCount: 20 } },
      { type: 'reflection', data: { count: 10 } },
      { type: 'notification', data: { queueSize: 8 } },
    ],
  },
  {
    id: 'journey-completion',
    name: 'Journey Completion',
    description: 'Validate milestone — final milestone reached, reflection generated, archive prepared.',
    category: 'experience',
    version: '1.0.0',
    compatibleVersion: '0.1.0',
    createdAt: '2025-01-01T00:00:00Z',
    author: 'system',
    components: [
      { type: 'runtime', data: { state: 'returning' } },
      { type: 'relationship', data: { trustScore: 55, stage: 'trusted_companion', sharedExperienceCount: 30 } },
      { type: 'memory', data: { count: 35 } },
      { type: 'discovery', data: { count: 15, pending: 0 } },
      { type: 'journey', data: { count: 3, active: 0, completed: 1 } },
      { type: 'notebook', data: { pageCount: 25 } },
      { type: 'reflection', data: { count: 15 } },
      { type: 'notification', data: { queueSize: 1 } },
    ],
  },
];
