import type { CharacterProfile, CharacterRuntimeState, CompanionAppendMessageInput, CompanionHistoryInput, CompanionInsight, CompanionMessage, CuriosityTarget, DebugDataResetInput, DebugDataResetResult, DiaryEntry, Discovery, DiscoveryCandidate, DiscoveryFeedback, DiscoveryStatus, ExplorationCycle, ExplorationLoopEvent, ExplorationPlan, InterestEdge, InterestGraph, InterestNode, Journey, JourneyMilestone, MemoryEdge, MemoryNode, Pattern } from '@our-companion/shared';
import type { ActionPermissionState } from '@our-companion/shared';
export interface DatabaseServiceOptions {
    path?: string;
}
export declare class DatabaseService {
    private readonly db;
    constructor(options?: DatabaseServiceOptions);
    close(): void;
    seedAnn(): void;
    getCharacterState(characterId?: string): CharacterRuntimeState;
    saveCharacterState(state: CharacterRuntimeState): CharacterRuntimeState;
    getActiveCharacters(): CharacterProfile[];
    getCharacterBehaviorRules(characterId?: string): Record<string, unknown>;
    setPrimaryCharacter(characterId: string): CharacterProfile;
    insertMemoryNode(node: MemoryNode): MemoryNode;
    updateMemoryNode(node: MemoryNode): MemoryNode;
    deleteMemoryNode(id: string): void;
    getMemoryNode(id: string): MemoryNode | undefined;
    listMemoryNodes(): MemoryNode[];
    insertMemoryEdge(edge: MemoryEdge): MemoryEdge;
    listMemoryEdges(): MemoryEdge[];
    insertDiscovery(discovery: Discovery): Discovery;
    updateDiscoveryStatus(id: string, status: DiscoveryStatus): Discovery;
    getDiscovery(id: string): Discovery | undefined;
    listDiscoveries(input?: {
        status?: DiscoveryStatus;
        limit?: number;
    }): Discovery[];
    countSharedToday(): number;
    getAnnouncedDiscoveryIds(): string[];
    isDiscoveryAnnounced(id: string): boolean;
    markDiscoveryAnnounced(id: string): void;
    listUnannouncedShared(limit?: number): Discovery[];
    insertPattern(pattern: Pattern): Pattern;
    listPatterns(userId?: string, limit?: number): Pattern[];
    upsertInterestGraph(graph: InterestGraph): InterestGraph;
    insertInterestNode(node: InterestNode): InterestNode;
    insertInterestEdge(edge: InterestEdge): InterestEdge;
    getInterestGraph(userId?: string): InterestGraph;
    insertCuriosityTarget(target: CuriosityTarget): CuriosityTarget;
    getCuriosityTarget(id: string): CuriosityTarget | undefined;
    insertExplorationPlan(plan: ExplorationPlan): ExplorationPlan;
    getExplorationPlan(id: string): ExplorationPlan | undefined;
    insertDiscoveryCandidate(candidate: DiscoveryCandidate): DiscoveryCandidate;
    getDiscoveryCandidate(id: string): DiscoveryCandidate | undefined;
    insertCompanionInsight(insight: CompanionInsight): CompanionInsight;
    getCompanionInsight(id: string): CompanionInsight | undefined;
    insertExplorationCycle(cycle: ExplorationCycle): ExplorationCycle;
    getExplorationCycle(id: string): ExplorationCycle | undefined;
    getCurrentExplorationCycle(): ExplorationCycle | undefined;
    listExplorationCycles(limit?: number): ExplorationCycle[];
    insertExplorationEvent(event: ExplorationLoopEvent): ExplorationLoopEvent;
    listCuriosityTargets(userId?: string, limit?: number): CuriosityTarget[];
    listDiscoveryCandidates(userId?: string, limit?: number): DiscoveryCandidate[];
    listCompanionInsights(userId?: string, limit?: number): CompanionInsight[];
    listExplorationEvents(cycleId?: string, limit?: number): ExplorationLoopEvent[];
    listExplorationEventsForCycle(cycleId: string): ExplorationLoopEvent[];
    insertDiscoveryFeedback(feedback: DiscoveryFeedback): DiscoveryFeedback;
    listDiscoveryFeedback(limit?: number): DiscoveryFeedback[];
    insertJourney(journey: Journey): Journey;
    listActiveJourneys(): Journey[];
    insertMilestone(milestone: JourneyMilestone): JourneyMilestone;
    listMilestones(journeyId?: string): JourneyMilestone[];
    insertDiary(entry: DiaryEntry): DiaryEntry;
    listDiaryEntries(input?: {
        type?: DiaryEntry['type'];
        limit?: number;
    }): DiaryEntry[];
    getAppSetting<T>(key: string): T | undefined;
    setAppSetting<T>(key: string, value: T): T;
    getActionPermissions(): ActionPermissionState;
    setActionPermissions(state: ActionPermissionState): ActionPermissionState;
    getCompanionRetentionDays(): number;
    pruneCompanionMessages(retentionDays?: number): void;
    insertCompanionMessage(input: CompanionAppendMessageInput): CompanionMessage;
    listCompanionMessages(input?: CompanionHistoryInput): CompanionMessage[];
    listCompanionContext(characterId: string, limit: number): CompanionMessage[];
    clearCompanionMessages(characterId?: string): void;
    resetDebugData(input: DebugDataResetInput): DebugDataResetResult;
}
